### ISSUE TITLE
light==yellow

### ISSUE THREAD

**Issue by tofr** [raunakchowdhury/rm-rf#2]
sounds fun, potentially rich, but...

how does this heap algo work? bit unclear. 

other data structure / algo usage?

**Comment by raunakchowdhury** [comment]
Changes Made:
- Scrapped the heap algo due to inefficient runtime and lack of necessity in the program (it overcomplicates the simple algo of random selection)
- Added a running leaderboard and initial start screen.
   - The running leaderboard will be sorted automatically via QuickSort.
   - The median time taken will be displayed in the leaderboards page, and will be calculated via a minHeap and maxHeap. 
- Stockpiled on QAFee in preparation for next week.

**Comment by raunakchowdhury** [comment]
no u
